import { useState } from 'react'

const loanBoxStyle = {
  border: '1px solid #444',
  borderRadius: '8px',
  padding: '16px',
  marginBottom: '12px',
  backgroundColor: '#1a1a1a',
  color: 'white'
}

function MonteCarloTab({ loans, mcResults, setMcResults }) {
  const [chartImg, setChartImg] = useState(null)
  const [loading, setLoading] = useState(false)

  const runMonteCarlo = async () => {
    setLoading(true)

    // single call returns mc stats + matplotlib chart from Python
    const res = await fetch("http://localhost:8000/analyze/monte-carlo", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        loans
      })
    })

    const data = await res.json()
    setMcResults(data)
    setChartImg(data.chart)
    setLoading(false)
  }

  return (
    <div>
      <p style={{ color: '#aaa', marginBottom: '16px', maxWidth: '600px' }}>
        Monte Carlo runs your loans through <strong style={{ color: 'white' }}>1,000 simulated lives</strong> — each
        slightly different. Some months income is higher, some months a surprise expense hits.
        The result is a <strong style={{ color: 'white' }}>range of payoff times</strong> rather than one fixed number.
      </p>
      <button onClick={runMonteCarlo} disabled={loading}>
        {loading ? 'Running 1,000 simulations...' : 'Run Monte Carlo'}
      </button>
      {mcResults && (
        <div style={{ marginTop: '24px' }}>
          {/* result cards */}
          <div style={{ display: 'flex', gap: '20px', marginBottom: '30px', flexWrap: 'wrap' }}>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold', marginBottom: '12px', color: '#8884d8' }}>Avalanche Strategy</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '10px' }}>
                Payoff time varies by <strong style={{ color: 'white' }}>{mcResults.avalanche.worst_case - mcResults.avalanche.best_case} months</strong> depending on life circumstances
              </p>
              <p>Best case: <strong>{mcResults.avalanche.best_case} months</strong> ({(mcResults.avalanche.best_case / 12).toFixed(1)} years)</p>
              <p>Median: <strong>{mcResults.avalanche.median} months</strong> ({(mcResults.avalanche.median / 12).toFixed(1)} years)</p>
              <p>Worst case: <strong>{mcResults.avalanche.worst_case} months</strong> ({(mcResults.avalanche.worst_case / 12).toFixed(1)} years)</p>
            </div>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold', marginBottom: '12px', color: '#82ca9d' }}>Snowball Strategy</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '10px' }}>
                Payoff time varies by <strong style={{ color: 'white' }}>{mcResults.snowball.worst_case - mcResults.snowball.best_case} months</strong> depending on life circumstances
              </p>
              <p>Best case: <strong>{mcResults.snowball.best_case} months</strong> ({(mcResults.snowball.best_case / 12).toFixed(1)} years)</p>
              <p>Median: <strong>{mcResults.snowball.median} months</strong> ({(mcResults.snowball.median / 12).toFixed(1)} years)</p>
              <p>Worst case: <strong>{mcResults.snowball.worst_case} months</strong> ({(mcResults.snowball.worst_case / 12).toFixed(1)} years)</p>
            </div>
            <div style={{ ...loanBoxStyle, borderColor: '#666' }}>
              <p style={{ fontWeight: 'bold', marginBottom: '8px' }}>What does this mean?</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', lineHeight: '1.6' }}>
                The <strong style={{ color: 'white' }}>median</strong> is your most likely payoff time.<br /><br />
                A smaller gap between best and worst case means your plan is more <strong style={{ color: 'white' }}>robust</strong> to real-life surprises.
              </p>
            </div>
          </div>
          {/* matplotlib chart from Python */}
          {chartImg && (
            <div>
              <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Payoff Range Comparison</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '12px' }}>Chart generated by Python Matplotlib</p>
              <img src={chartImg} alt="Monte Carlo results chart" style={{ width: '100%', borderRadius: '8px' }} />
            </div>
          )}

        </div>
      )}
    </div>
  )
}

export default MonteCarloTab
