import { useState } from 'react'

// shared box style used across result cards
const loanBoxStyle = {
  border: '1px solid #444',
  borderRadius: '8px',
  padding: '16px',
  marginBottom: '12px',
  backgroundColor: '#1a1a1a',
  color: 'white'
}

function OptimizeTab({ loans, results, setResults }) {
  const [chartImg, setChartImg] = useState(null)
  const [loading, setLoading] = useState(false)

  const optimize = async () => {
    setLoading(true)

    // single call returns stats + matplotlib chart from Python
    const res = await fetch("http://localhost:8000/analyze/optimize", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ loans, extra_payment: 100 })
    })

    const data = await res.json()
    setResults(data)
    setChartImg(data.chart)  // base64 PNG generated by Matplotlib
    setLoading(false)
  }

  return (
    <div>
      <button onClick={optimize} disabled={loading}>
        {loading ? 'Running...' : 'Run Optimize'}
      </button>

      {results && chartImg && (
        <div style={{ display: 'flex', gap: '40px', marginTop: '30px', alignItems: 'flex-start' }}>

          {/* stats column */}
          <div style={{ minWidth: '250px' }}>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold', marginBottom: '8px', color: '#8884d8' }}>Avalanche</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '8px' }}>Highest interest rate first</p>
              <p>Months to payoff: <strong>{results.avalanche.months}</strong> ({(results.avalanche.months / 12).toFixed(1)} years)</p>
              <p>Total interest: <strong>${results.avalanche.total_interest.toLocaleString()}</strong></p>
            </div>

            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold', marginBottom: '8px', color: '#82ca9d' }}>Snowball</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '8px' }}>Smallest balance first</p>
              <p>Months to payoff: <strong>{results.snowball.months}</strong> ({(results.snowball.months / 12).toFixed(1)} years)</p>
              <p>Total interest: <strong>${results.snowball.total_interest.toLocaleString()}</strong></p>
            </div>

            <div style={{ ...loanBoxStyle, borderColor: '#666' }}>
              <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Recommendation</p>
              <p style={{ color: '#aaa', fontSize: '0.9rem' }}>
                {results.avalanche.total_interest <= results.snowball.total_interest
                  ? 'Avalanche saves you more money in total interest'
                  : 'Snowball gets you debt-free faster'}
              </p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginTop: '8px' }}>
                Interest difference: ${Math.abs(results.avalanche.total_interest - results.snowball.total_interest).toLocaleString()}
              </p>
            </div>
          </div>

          {/* chart column — image generated by Python Matplotlib */}
          <div style={{ flex: 1 }}>
            <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Balance Over Time</p>
            <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '10px' }}>Chart generated by Python Matplotlib</p>
            <img src={chartImg} alt="Balance over time" style={{ width: '100%', borderRadius: '8px' }} />
          </div>

        </div>
      )}
    </div>
  )
}

export default OptimizeTab
