import { useState } from 'react'

const loanBoxStyle = {
  border: '1px solid #444',
  borderRadius: '8px',
  padding: '16px',
  marginBottom: '12px',
  backgroundColor: '#1a1a1a',
  color: 'white'
}

function ScheduleTab({ loans, schedule, setSchedule }) {
  const [chartImg, setChartImg] = useState(null)
  const [loading, setLoading] = useState(false)

  const runSchedule = async () => {
    setLoading(true)

    // single call returns table + summary + matplotlib chart
    const res = await fetch("http://localhost:8000/analyze/schedule", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ loans, extra_payment: 100 })
    })

    const data = await res.json()
    setSchedule(data)
    setChartImg(data.chart)
    setLoading(false)
  }

  return (
    <div>
      <p style={{ color: '#aaa', marginBottom: '16px', maxWidth: '600px' }}>
        Full month-by-month breakdown of every payment — how much goes to interest vs principal,
        and your running total. Built using <strong style={{ color: 'white' }}>Pandas DataFrames</strong> in Python.
      </p>
      <button onClick={runSchedule} disabled={loading}>
        {loading ? 'Generating...' : 'Generate Schedule'}
      </button>

      {schedule && (
        <div style={{ marginTop: '20px' }}>

          {/* summary boxes */}
          <div style={{ display: 'flex', gap: '20px', marginBottom: '20px' }}>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold' }}>Total months</p>
              <p>{schedule.summary.total_months} months ({(schedule.summary.total_months / 12).toFixed(1)} years)</p>
            </div>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold' }}>Total interest paid</p>
              <p style={{ color: '#ff6b6b' }}>${schedule.summary.total_interest_paid.toLocaleString()}</p>
            </div>
            <div style={loanBoxStyle}>
              <p style={{ fontWeight: 'bold' }}>Total principal paid</p>
              <p style={{ color: '#82ca9d' }}>${schedule.summary.total_principal_paid.toLocaleString()}</p>
            </div>
          </div>

          {/* matplotlib chart */}
          {chartImg && (
            <div style={{ marginBottom: '30px' }}>
              <p style={{ fontWeight: 'bold', marginBottom: '4px' }}>Payment Breakdown Charts</p>
              <p style={{ color: '#aaa', fontSize: '0.85rem', marginBottom: '12px' }}>Generated by Python Matplotlib</p>
              <img src={chartImg} alt="Amortization schedule chart" style={{ width: '100%', borderRadius: '8px' }} />
            </div>
          )}

          {/* data table */}
          <p style={{ fontWeight: 'bold', marginBottom: '8px' }}>Full Amortization Table</p>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #444' }}>
                  <th style={{ padding: '8px', textAlign: 'left',  color: '#aaa' }}>Month</th>
                  <th style={{ padding: '8px', textAlign: 'right', color: '#aaa' }}>Total Balance</th>
                  <th style={{ padding: '8px', textAlign: 'right', color: '#aaa' }}>Interest Paid</th>
                  <th style={{ padding: '8px', textAlign: 'right', color: '#aaa' }}>Principal Paid</th>
                  <th style={{ padding: '8px', textAlign: 'right', color: '#aaa' }}>Cumulative Interest</th>
                </tr>
              </thead>
              <tbody>
                {schedule.schedule.map((row, i) => (
                  <tr key={i} style={{ borderBottom: '1px solid #222' }}>
                    <td style={{ padding: '8px', color: 'white' }}>{row.month}</td>
                    <td style={{ padding: '8px', textAlign: 'right', color: 'white'   }}>${row.total_balance.toLocaleString()}</td>
                    <td style={{ padding: '8px', textAlign: 'right', color: '#ff6b6b' }}>${row.total_interest.toLocaleString()}</td>
                    <td style={{ padding: '8px', textAlign: 'right', color: '#82ca9d' }}>${row.total_principal.toLocaleString()}</td>
                    <td style={{ padding: '8px', textAlign: 'right', color: '#aaa'    }}>${row.cumulative_interest.toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

        </div>
      )}
    </div>
  )
}

export default ScheduleTab
